### ISSUE TITLE
Boom library and other faulty error handling causing requests to hang in may failure conditions

### ISSUE THREAD

**Issue by ryanolee** [evolv-ai/serverless-offline-edge-lambda#192]
## What?
The `boom` library seems to either be problematic or has implemented a number of breaking changes since this package was last published. A wide range of errors will cause requests to the offline dev handler to hang requests. Hanging requests are exceedingly hard to debug without tearing into the package and working out why.

## How?
In many `catch` statements reraise unexpected errors cause the "catch step" to fail entierley. This causes the request to hang and the exception to be blackholes.

## What we might want to do about this?
We may want to try to simplify the errors and remove / reduce use of the `boom` library given we only seem to use it for transporting 500 and 404 errors. It seems rather heavy for what it offers. An internal set of 2 errors we can add to the `src/errors` directory will likely fill in the same role without causing the wide range of issues the `boom` package is seemingly causing.

**Comment by mattstrom** [comment]
Thanks again for the contribution! Published package is available here. CircleCI was giving me some problems. So let me know if the package doesn't work:
https://www.npmjs.com/package/serverless-offline-edge-lambda/v/1.1.0

It's hard to find time to patch these support libraries when there are other business priorities.

**Comment by ryanolee** [comment]
Thank you very much @mattstrom for the really quick turnaround ♥️! I fully understand the plight of having many other things popup and how that tends to make it difficult to maintain this sort of stuff 😅. I will certainly install the package and get back to you if I broke anything while I was in there /  create a new issue + pr for it. Thanks for making all of this stuff public. Has been a great help in getting efficient local dev workflows setup!

**Comment by ryanolee** [comment]
Release looks to work! We might want to check how errors get handled by caches. But the intimidate issue of hanging requests has been resolved. Thanks @matthewstrom !
